name: rebuild-cache

on:
  pull_request:
  push:
    branches:
      - main
    paths:
      - "src/localBreeds.json"
      - "src/fallbackBreeds.json"
      - "src/breedignore"

jobs:
  rebuild-cache:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Run cache download
        run: docker compose exec -T breeds sh -c "npm run process"

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Cache rebuild
