name: Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  code-quality-and-validation:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    concurrency:
      group: test-${{ github.ref_name }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v7

      - name: Setup Node
        uses: actions/setup-node@v7
        with:
          node-version-file: .node-version

      - name: Install dependencies
        run: npm install

      - name: Run formatting checks
        run: npm run fmt:check

      - name: Run linting
        run: npm run lint

      - name: Run typescript checks
        run: npm run ts:check
